e1 = input('Digite algo: ')

print(type(e1))
print('Is it alfanum? {} haha'.format(e1.isalnum()))
print('Is it alpha? {} hehe'.format(e1.isalpha()))
print('Is it decimal? {} kaka'.format(e1.isdecimal()))
print('Is it digit? {} shaus'.format(e1.isdigit()))
print('Is it identifier? {} rsrs'.format(e1.isidentifier()))
print('Is it lower? {} ksks'.format(e1.islower()))
print('Is it numeric? {} ksks'.format(e1.isnumeric()))
print('Is it printable? {} ksks'.format(e1.isprintable()))
print('Is it space? {} ksks'.format(e1.isspace()))
print('Is it title? {} ksks'.format(e1.istitle()))
print('Is it upper? {} ksks'.format(e1.isupper()))